import { NextResponse } from 'next/server';
import { verifyRequestAuth } from '@/lib/auth';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export async function POST(request: Request) {
    const user = verifyRequestAuth(request);
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    try {
        const { matches, title } = await request.json();

        if (!matches || !Array.isArray(matches)) {
            return NextResponse.json({ error: 'matches array is required' }, { status: 400 });
        }

        const inStockItems = matches.filter((m: any) => m.inStock && m.confidence >= 0.7);

        const pdf = await PDFDocument.create();
        const font = await pdf.embedFont(StandardFonts.Helvetica);
        const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

        const pageWidth = 595;
        const pageHeight = 842;
        const margin = 50;
        const lineHeight = 18;
        const colWidths = [30, 200, 80, 80, 100];

        let page = pdf.addPage([pageWidth, pageHeight]);
        let y = pageHeight - margin;

        page.drawText(title || 'Warehouse Parts - Project Match', {
            x: margin, y, size: 16, font: fontBold, color: rgb(0.1, 0.1, 0.1),
        });
        y -= 12;

        page.drawText(`${inStockItems.length} items found in warehouse`, {
            x: margin, y, size: 10, font, color: rgb(0.5, 0.5, 0.5),
        });
        y -= 8;

        page.drawText(new Date().toLocaleDateString('he-IL'), {
            x: margin, y, size: 9, font, color: rgb(0.5, 0.5, 0.5),
        });
        y -= 25;

        page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 1, color: rgb(0.2, 0.2, 0.2) });
        y -= 15;

        const headers = ['#', 'Part', 'Part No.', 'Needed', 'In Stock'];
        let xPos = margin;
        headers.forEach((h, i) => {
            page.drawText(h, { x: xPos, y, size: 9, font: fontBold, color: rgb(0.3, 0.3, 0.3) });
            xPos += colWidths[i];
        });
        y -= 6;

        page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: rgb(0.8, 0.8, 0.8) });
        y -= lineHeight;

        for (let i = 0; i < inStockItems.length; i++) {
            if (y < margin + 30) {
                page = pdf.addPage([pageWidth, pageHeight]);
                y = pageHeight - margin;
            }

            const item = inStockItems[i];
            xPos = margin;

            const row = [
                String(i + 1),
                truncate(item.inventoryMatch || item.projectPart || '', 35),
                truncate(item.inventoryPartNumber || '-', 12),
                String(item.quantityNeeded || '-'),
                String(item.quantityInStock || '-'),
            ];

            if (i % 2 === 0) {
                page.drawRectangle({
                    x: margin - 4, y: y - 3, width: pageWidth - 2 * margin + 8, height: lineHeight, color: rgb(0.97, 0.97, 0.97),
                });
            }

            row.forEach((cell, j) => {
                page.drawText(cell, { x: xPos, y, size: 9, font, color: rgb(0.15, 0.15, 0.15) });
                xPos += colWidths[j];
            });

            y -= lineHeight;
        }

        y -= 10;
        page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: rgb(0.8, 0.8, 0.8) });
        y -= 15;
        page.drawText('Generated by Factory Records', { x: margin, y, size: 8, font, color: rgb(0.7, 0.7, 0.7) });

        const pdfBytes = await pdf.save();

        return new Response(Buffer.from(pdfBytes), {
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="warehouse-match-${Date.now()}.pdf"`,
            },
        });
    } catch (error: any) {
        console.error('PDF export failed:', error);
        return NextResponse.json({ error: error.message || 'Export failed' }, { status: 500 });
    }
}

function truncate(str: string, max: number): string {
    return str.length > max ? str.slice(0, max - 2) + '..' : str;
}
